// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG6j6tqL0OUrParOJvJ-GusGCJcEBGAbg',
    appId: '1:256539168332:web:81e48c23f0387d1cc76ee9',
    messagingSenderId: '256539168332',
    projectId: 'evently-c19-a4ddf',
    authDomain: 'evently-c19-a4ddf.firebaseapp.com',
    storageBucket: 'evently-c19-a4ddf.firebasestorage.app',
    measurementId: 'G-JWFGPHMGXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeeQPI42AOUd2lKWUqFLfcFq9sIlGd81E',
    appId: '1:256539168332:android:bf538cc31948ac5ac76ee9',
    messagingSenderId: '256539168332',
    projectId: 'evently-c19-a4ddf',
    storageBucket: 'evently-c19-a4ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9MP7ZLUCOCGs0579Hgo99z5QdBmFJmHU',
    appId: '1:256539168332:ios:df6fa3e1bc1b5aa0c76ee9',
    messagingSenderId: '256539168332',
    projectId: 'evently-c19-a4ddf',
    storageBucket: 'evently-c19-a4ddf.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9MP7ZLUCOCGs0579Hgo99z5QdBmFJmHU',
    appId: '1:256539168332:ios:df6fa3e1bc1b5aa0c76ee9',
    messagingSenderId: '256539168332',
    projectId: 'evently-c19-a4ddf',
    storageBucket: 'evently-c19-a4ddf.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG6j6tqL0OUrParOJvJ-GusGCJcEBGAbg',
    appId: '1:256539168332:web:6b94fd34a9421e66c76ee9',
    messagingSenderId: '256539168332',
    projectId: 'evently-c19-a4ddf',
    authDomain: 'evently-c19-a4ddf.firebaseapp.com',
    storageBucket: 'evently-c19-a4ddf.firebasestorage.app',
    measurementId: 'G-EJE7W302WZ',
  );
}
